stages: [check]

check_sherif:
  image: node:24-alpine
  stage: check
  script:
    - node -v
    - corepack enable
    - corepack prepare pnpm@11.5.0 --activate
    - pnpm -v
    - echo "Printing packages/api/package.json for verification:"
    - cat packages/api/package.json
    - pnpm dlx sherif@1.6.1
